{% set name = "buildbot-www" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f9988e91364b770aac65f0295ba690c683646dc142681e011c48cc4d9225f918

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >3.5
    - mock
    - buildbot
    - buildbot-pkg
  run:
    - python >3.5
    - mock
    - buildbot
    - buildbot-pkg

test:
  imports:
    - buildbot_www
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://buildbot.net/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Buildbot UI
  doc_url: https://docs.buildbot.net

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
    - marcelotrevisani
