{% set name = "buildbot-www" %}
{% set version = "4.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c70bb6eb47dc45f9d46ab116ddd9cc725f1885e47462660280d406cbb2da0c6c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - mock
    - buildbot
    - buildbot-pkg
  run:
    - python >={{ python_min }}
    - mock
    - buildbot
    - buildbot-pkg

test:
  imports:
    - buildbot_www
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://buildbot.net/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Buildbot UI
  doc_url: https://docs.buildbot.net

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
    - marcelotrevisani
