{% set name = "buildbot-www" %}
{% set version = "3.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1e5cb577051b59b947a0ffae7e3c72cf86e85dbcbc9317854872cc1dc0a9735a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >3.5
    - mock
    - buildbot
    - buildbot-pkg
  run:
    - python >3.5
    - mock
    - buildbot
    - buildbot-pkg

test:
  imports:
    - buildbot_www
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://buildbot.net/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Buildbot UI
  doc_url: https://docs.buildbot.net

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
    - marcelotrevisani
