travis:
  secure:
    BINSTAR_TOKEN: KjpnlzWUu98YBxLphE8HogejBzOxQvWLrDNDPVJTAFpEwiAUZScATtZAeyRsZfEYzg//b3XF8UdlWM8QbbN8d3wf3ZP3K3GaCNd0fjuMqbqp9JIcwAMVMCtcWePZupRy/8dR3WlndvA4JDwCExVwth4IXsRlBQkk6/RGnq2dWy6pd4rKlBlxV9CmhhsO6oFFLUXIILZkTyTJB0Hgd613eQDFiAS05FKoj+IngwgsVlXYS8d5njT6Y9PFinDxcQ/CbimipWTd1oiwXUTwWxwkgyNRCdClxDNqxHZIABXRQfThSoU35oO/149dj2MjHlRQm9SI7YTXzz6zXbVjwGizfK3MsFWN+krCA+fsrMxHx2WtcCQFmb6Msd2fA1Oq7yc3iPOJTR3G1xGYJBq4G/AMkOTuGIOAF7pp8eGYe/PoJqVBSrsUTkY441ZeHkV3FPa0I31bBiCycw/0UHJ08pIh6Sso7TC9U0yx/oUWK9DUaURvUOwX0P0apCQfJhbb+RPghjS44NuyaHW/n1jp3+8fuLYQ2wpQC3lMMSwIjSXOcjhC6tGvL9TK2/gB+z894CH8H8/yMvE6dIuNlKxNhw0/Cgbn4ZySbjRyWjpGybHhT3UabzRA2kMY9lZa3WPuSiNPBDl3NvZF08tclJf+Gu7UbU0XTOlDMrQVf+nZut1Kk4A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
